build: off
deploy: off

environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@3 --global
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run tap
  - npm run mocha
  - npm run lint
