build: off
deploy: off

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "3"
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm@3 --global
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run lint
